### PR TITLE
Preset quaternion vector based on selected strut for VefImportDialog

### PR DESCRIPTION
**Pull request by david-hall**
QuaternionPanel tool tip says "To pre-set the i, j, and k values, select a single strut before opening this dialog." That worked as described for PolytopesDialog. Now it also works for VefImportDialog.

### CODE REVIEW

**Comment by vorth** [comment]
Does the "setQuaternion" action do the right thing when there is no strut (or multiple struts) selected?

**Comment by david-hall** [comment]
Yes. If no struts are selected,or more than 1 strut is selected it retains
the last value just like the polytope dialog.

**Comment by david-hall** [comment]
I just merged master into this branch and verified that it still behaves as
expected.

**Comment by david-hall** [comment]
I just merged master into this branch again as we discussed. I also made 2 trivial commits to eliminate a compile warning. I've merged this branch into the number-panel-menu branch (PR # 458) so you can ignore this PR if you're ready to accept #458. Otherwise, you can just accept this one on its own for now.

**Pull request merged**
