### PR TITLE
Add context menu to NumberPanel

### PR DESCRIPTION
**Pull request by david-hall**
Menu actions include Show Decimal Value, Reset to Zero, Set to One and Negate
This applies to the Mesh Import scale and quaternion dialog as well as the quaternion panel in the Generate Polytope dialog.

### CODE REVIEW

**Comment by vorth** [comment]
Nice!

One request, though: put the "show decimal value" at the bottom.

**Comment by david-hall** [comment]
I just made some significant improvements to the context menu. Now it can set the number to common field-specific values like phi and root2. I didn't notice your request to move "show decimal value" until just now. I'll let you review it again with the new changes. If you still want it moved to the bottom, let me know and I'll do it.

**Comment by david-hall** [comment]
I discovered that some inconsistencies in the way legacy fields implemented getIrrational() were causing incorrect results from getNumberByName(). I refactored getIrrational() in all of the legacy fields so that they all behave consistently now and I added a new test case to ensure it's so. The change is in the newest commit to this branch. Take a look at the comments in that commit for more details.

**Comment by david-hall** [comment]
I also added some JavaDocs comments to a few methods.

**Comment by david-hall** [comment]
I moved "Show Decimal Value" to the bottom of the NumberPanel context menu as you requested.

**Comment by david-hall** [comment]
I merged master into the fix-vef-quaternion branch then merged that branch into this one and checked that everything behaves as expected. If you're ready to accept this PR then you don't need PR # 457 at all since it's all included here now.

**Comment by david-hall** [comment]
Thanks for fixing the recent regression failures. I've merged master into this branch so it's up to date again and ready for you to merge into master. Let me know if you have any questions or concerns.

**Pull request merged**
